config/routes.rb
Air::Application.routes.draw do

  root to: 'flights#index'
  
  resources :users
  
  get '/signin', :to => 'sessions#new'
  get '/signout', :to  => 'sessions#destroy', as: :signout
  post 'sessions/create'
  
  get '/help' => 'pages#help', :as => :help
  get '/mockup'  =>  'pages#home', :as  => :mockup
  
  get '/reservations/new', :to  =>  'reservations#new', as: :new_reservation
  get '/reservations/create', :to  => 'reservations#create', as: :reservations
  get '/reservations/show', :to  => 'reservations#show', as: :reservation
  get '/reservations/destroy', :to  =>  'reservations#destroy', as: :cancel_reservation
  
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :arrival_code, :depart_code, :depart_time, :distance, :flight_number

  before_save :calculate_distance

  def calculate_distance
     self.distance = (MileageCalculator.new(self.depart_code, self.arrival_code)).miles
  end
end

app/models/mileage_calculator.rb
class MileageCalculator
  
  CHART = { "ORD-SFO"  => 1846,
            "ORD-BOS"  => 867,
            "ORD-LAX"  => 1745,
            "ORD-JFK"  => 740,
            "SFO-BOS"  => 2704,
            "SFO-JFK"  => 2586,
            "SFO-LAX"  => 337,
            "BOS-JFK"  => 187,
            "BOS-LAX"  => 2611,
            "JFK-LAX"  => 2475
          }
  
  def initialize(departure_airport_code, arrival_airport_code)
    @departure_airport_code = departure_airport_code
    @arrival_airport_code = arrival_airport_code
  end
  
  def miles
       miles = CHART["#{@departure_airport_code}-#{@arrival_airport_code}"]
     if miles.nil?
       miles = CHART["#{@arrival_airport_code}-#{@departure_airport_code}"]
     end
     return miles  
  end
  
  def duration
    
  end
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :card_number, :date, :flight_id, :user_id
  
  belongs_to :user
  belongs_to :flight
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :flyer_miles, :last_name, :password, :password_confirmation
  
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  
  before_create :start_miles_at_zero
  
  def start_miles_at_zero
    self.miles = 0
  end
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :first_name, :presence => true, :length  => { maximum: 15 }
  validates :last_name, :presence  => true, :length  => { minimum: 5 }
  validates :email, :presence => true,
                      :format =>      { with: VALID_EMAIL_REGEX },
                      :uniqueness  => { case_sensitive: false }
  validates :password, :length => { minimum: 6 }
  validates :password_confirmation, :presence => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :show_sessions_data
  before_filter :current_user
  
  def current_user
    @user = User.find_by_id(session[:uid])
  end
  
  def show_sessions_data
    logger.debug '*' *30
    logger.debug "Session: #{session.inspect}"
    logger.debug '*' *30
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index
    @flights = Flight.all
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def new
    if session[:uid].nil?
          redirect_to root_url, notice: "Nice try!"
          return
    end
        
        @reservation = Reservation.new
        @reservation.flight = Flight.find(params[:flight_id])
  end
  
  
  def create
  end
  
  def show
  end
  
  def destroy
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:uid] = user.id
      redirect_to root_url
    else
      flash.now[:notice] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Come again soon!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to "/", notice: "Good work, you\'re a member"
    else
      flash.now[:notice] = 'Invalid email/password'
      render "users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt:user.first_name, class: "gravatar")
  end
end

app/views/flights/index.html.erb
<h2>Daily Flight Schedule</h2>

<div id="search">
	<label for="keyword">Search:</label><input type="text" name="keyword" placeholder="Enter an Airport Code" size="30">
</div>

<table>
  <thead>
    <tr>
      <th>
      <th>Flight Number</th>
      <th>Leaves</th>
      <th>Time</th>
      <th>Arrives</th>
      <th>Time</th>
      <th>Seats Remaining</th>
      <th>Miles</th>
    </tr>
  </thead>
  <tbody>
	<% @flights.each do |flight| %>
    <tr>
      <td><%= link_to "Book Now", new_reservation_url(flight_id: flight.id) %></td>
      <td><%= flight.flight_number %></td>
      <td><%= flight.depart_code %></td>
      <td><%= flight.depart_time.strftime('%l:%M %P') %></td>
      <td><%= flight.arrival_code %></td>
      <td>--</td>
      <td>--</td>
      <td><%= flight.distance %></td>
			<% end %>
    </tr>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Academy Air</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="container">
		<header>
			<h1><%= link_to "Academy Air", root_url %></h1>
			<nav>
				<ul>
					<% if session[:uid].present? %>
					<li><%= link_to "View My Profile", user_url(@user) %></li>
					<li><%= link_to "Sign Out", signout_url %></li>
					<% else %>
					<li><%= link_to "Sign In", signin_url %></li>
					<li><%= link_to "Sign Up", new_user_url %></li>
					<% end %>
					<li><%= link_to "Help", help_url %></li>
				</ul>
			</nav>
			<% if session[:uid].present?  %>
				<p>Hello, <%= @user.first_name %></p>
			<% end %>
			<p>
			<% if flash[:notice] %>
			<p class="notice"><%= flash[:notice] %></p>
			<% end %>
			</p>
		</header>

		<div id="content">
			<%= yield %>
		</div>
		
		<footer>
			&copy;2012 Academy Air, Inc.  Got comments or suggestions? Keep 'em to yourself!
		</footer>
	</div>
</body>
</html>

app/views/pages/help.html.erb
<div id="help">

<p><strong>MVP User Stories</strong></p>

<ol>
  <li>As a visitor, I want to see the list of flights that are available each day.
      <span><br/>HINT: Don't worry about mileage or duration at first.  When you're ready, use the MileageCalculator callback to calculate those when needed.</span></li>
			<p><em>DONE</em></p>
  <li>As a visitor, I want to create a user account, so that I can make reservations.</li>
			<p><em>DONE</em></p>
  <li>As a visitor, I want to get to the Sign Up form so that I can create an account.</li>
			<p><em>DONE</em></p>
  <li>As a visitor, I want to sign in.</li>
			<p><em>DONE</em></p>
  <li>As a visitor, I want to sign out.</li>
			<p><em>DONE</em></p>
  <li>As a user, I want to see a profile page that shows how many frequent flyer miles I’ve earned.</li>
	<p><em>DONE</em></p>
  <li>As a user, I want to make a reservation.</li>
  <li>As a user, I expect my frequent flyer mileage total to increase every time I reserve a flight.</li>
  <li>As a user, I want to see my reservations in my account profile.</li>
  <li>As a user, I want to search for flights by airport code.</li>
  <li>As a user, I want to search for flights by airport code or city name.</li>
  <li>As a user, I want to first see my account profile when I login.</li>
  <li>As a user, I want to receive an email confirming my reservation.</li>
</ol>

<p id="ground_rules"><strong>Ground Rules (get it?)</strong></p>
<ol>
  <li>Planes fly at about 8 miles per minute, so the arrival time and flight duration could, in theory, be calculated rather than stored in the database.</li>
  <li>Every Academy Air flight costs the same: $70.</li>
  <li>We only accept Visa credit cards.  Visa cards are 16-digits numbers that always start with the number 4.</li>
</ol>


</div>

app/views/pages/home.html.erb
<h2>Daily Flight Schedule</h2>

<div id="search">
	<label for="keyword">Search:</label><input type="text" name="keyword" placeholder="Enter an Airport Code" size="30">
</div>

<table>
  <thead>
    <tr>
      <th>
      <th>Flight Number</th>
      <th>Leaves</th>
      <th>Time</th>
      <th>Arrives</th>
      <th>Time</th>
      <th>Seats Remaining</th>
      <th>Miles</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><button>Book Now</button></td>
      <td>104</td>
      <td>ORD</td>
      <td>10:00 am</td>
      <td>SFO</td>
      <td>1:00 pm</td>
      <td>60</td>
      <td>1846</td>
    </tr>
    <tr>
      <td><button>Book Now</button></td>
      <td>216</td>
      <td>JFK</td>
      <td>10:00 am</td>
      <td>LAX</td>
      <td>1:00 pm</td>
      <td>8</td>
      <td>2475</td>
    </tr>
    <tr>
      <td></td>
      <td>908</td>
      <td>ORD</td>
      <td>10:00 am</td>
      <td>BOS</td>
      <td>1:00 pm</td>
      <td>0</td>
      <td>866</td>
    </tr>
    <tr>
      <td><button>Book Now</button></td>
      <td>761</td>
      <td>JFK</td>
      <td>10:00 am</td>
      <td>BOS</td>
      <td>1:00 pm</td>
      <td>42</td>
      <td>186</td>
    </tr>
    
  </tbody>
</table>

app/views/reservations/new.html.erb
<%= form_for(@reservation) do |f| %>
	<% if @reservation.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
			
			<ul>
				<% @reservation.errors.full_messages.each do |msg| %>
				<%= msg %>
				<% end %>
			</ul>
			</div>
	<% end %>
	
	<h2>Flight Number <%= @reservation.flight.flight_number %></h2>
	<h2>From: <%= @reservation.flight.depart_code %></h2>
	<h2>To: <%= @reservation.flight.arrival_code %></h2>
	
	<%= f.hidden_field :flight_id %>
	
	
	
	
<% end %>

app/views/users/new.html.erb
<h1>Sign Up with Academy Air</h1>

<% if @user.present? %>
	<div class="notice">
		
	<% @user.errors.full_messages.each do |message| %>
	<li ><%= message %></li>
	<% end %>
	</div>
	<% end %>


<%= form_for @user do |f| %>
	<p>
	<%= f.label :first_name, 'First Name' %>
	<%= f.text_field :first_name %>
	</p>
	<p>
	<%= f.label :last_name, 'Last Name' %>
	<%= f.text_field :last_name %>
	</p>
	<p>
	<%= f.label :email, 'Email' %>
	<%= f.text_field :email %>
	</p>
	<p>
	<%= f.label :password, 'Password' %>
	<%= f.password_field :password %>
	</p>
	<p>
	<%= f.label :password_confirmation, 'Password Confirmation' %>
	<%= f.password_field :password_confirmation %>
	</p>
	<p>
	<%= f.submit 'Join up!' %>
	</p>
	<% end %>

app/views/users/show.html.erb
<h1>Profile Page</h1>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<p><strong>Name: </strong><%= @user.first_name %> <%= @user.last_name %></p>
				<p><strong>Miles Earned:</strong></p>
				<p><%= @user.flyer_miles.to_i %></p>
				
		</h1>
	</section>
</div>